---
development:
  host: http://localhost
  port: 3000
  details_dir: details
  public_host: http://localhost:3000
  symbol: "-"

test:
  host: http://localhost
  port: 3000
  details_dir: spec/details
  public_host: http://localhost:3000
  symbol: "-"

production:
  host: http://localhost
  post: 4567
  details_dir: details
  public_host: http://nx.is
  symbol: "-"
