---
development:
  host: 127.0.0.1
  port: 3000
  details_dir: details
  public_host: http://localhost:3000
  symbol: "-"
  username: auth
  password: spacerobots1234

test:
  host: 127.0.0.1
  port: 3000
  details_dir: spec/details
  public_host: http://localhost:3000
  symbol: "-"
  username: auth
  password: spacerobots1234

production:
  host: 127.0.0.1
  port: 4567
  details_dir: details
  public_host: http://nx.is
  symbol: "-"
  username: auth
  password: spacerobots1234
